# -*- coding: utf-8 -*-
"""
Test suite for Package.py

@author: Generated by Antigravity
"""
import pytest
import os
import tempfile
from Package import Package


class TestPackageCreation:
    """Tests for Package initialization."""
    
    def test_package_creation_basic(self):
        """Test basic Package creation with all parameters."""
        pkg = Package(
            size=(10, 20, 30),
            weight=5.5,
            value=100.0,
            content_description="Electronics",
            is_dangerous=False,
            is_fragile=True
        )
        
        assert pkg.size == (10, 20, 30)
        assert pkg.weight == 5.5
        assert pkg.value == 100.0
        assert pkg.content_description == "Electronics"
        assert pkg.is_dangerous == False
        assert pkg.is_fragile == True
    
    def test_package_creation_dangerous(self):
        """Test Package creation with dangerous goods."""
        pkg = Package((5, 5, 5), 2.0, 50.0, "Batteries", True, False)
        
        assert pkg.is_dangerous == True
        assert pkg.is_fragile == False
    
    def test_package_creation_with_empty_description(self):
        """Test Package creation with empty description."""
        pkg = Package((1, 1, 1), 0.1, 10.0, "", False, False)
        
        assert pkg.content_description == ""


class TestPackageProperties:
    """Tests for Package property accessors."""
    
    @pytest.fixture
    def sample_package(self):
        """Create a sample package for testing."""
        return Package((15, 25, 35), 10.0, 500.0, "Furniture", False, True)
    
    def test_size_property(self, sample_package):
        """Test size property returns correct tuple."""
        assert sample_package.size == (15, 25, 35)
        assert len(sample_package.size) == 3
    
    def test_weight_property(self, sample_package):
        """Test weight property."""
        assert sample_package.weight == 10.0
    
    def test_value_property(self, sample_package):
        """Test value property."""
        assert sample_package.value == 500.0
    
    def test_properties_are_readonly(self, sample_package):
        """Test that properties don't have setters."""
        with pytest.raises(AttributeError):
            sample_package.size = (1, 1, 1)
        with pytest.raises(AttributeError):
            sample_package.weight = 1.0
        with pytest.raises(AttributeError):
            sample_package.value = 1.0


class TestPackageAddDescription:
    """Tests for add_description method."""
    
    def test_add_description_appends(self):
        """Test that add_description appends to existing description."""
        pkg = Package((1, 1, 1), 1.0, 10.0, "Books", False, False)
        
        pkg.add_description("Hardcover")
        
        assert "Books" in pkg.content_description
        assert "Hardcover" in pkg.content_description
    
    def test_add_description_multiple_times(self):
        """Test adding descriptions multiple times."""
        pkg = Package((1, 1, 1), 1.0, 10.0, "Initial", False, False)
        
        pkg.add_description("Second")
        pkg.add_description("Third")
        
        assert "Initial" in pkg.content_description
        assert "Second" in pkg.content_description
        assert "Third" in pkg.content_description
    
    def test_add_description_to_empty(self):
        """Test adding description to empty initial description."""
        pkg = Package((1, 1, 1), 1.0, 10.0, "", False, False)
        
        pkg.add_description("Added later")
        
        assert "Added later" in pkg.content_description


class TestPackageStr:
    """Tests for Package __str__ representation."""
    
    def test_str_contains_all_info(self):
        """Test that __str__ contains all package info."""
        pkg = Package((10, 20, 30), 5.0, 100.0, "Test Item", True, True)
        
        result = str(pkg)
        
        assert "(10, 20, 30)" in result
        assert "5" in result  # weight
        assert "100" in result  # value
        assert "Test Item" in result
        assert "Yes" in result  # dangerous and fragile


class TestPackageSnapshot:
    """Tests for snapshot and from_dict methods."""
    
    def test_snapshot_returns_dict(self):
        """Test that snapshot returns a dictionary."""
        pkg = Package((5, 10, 15), 3.0, 75.0, "Snapshot Test", False, True)
        
        snapshot = pkg.snapshot()
        
        assert isinstance(snapshot, dict)
        assert snapshot['size'] == (5, 10, 15)
        assert snapshot['weight'] == 3.0
        assert snapshot['value'] == 75.0
        assert snapshot['content_description'] == "Snapshot Test"
        assert snapshot['is_dangerous'] == False
        assert snapshot['is_fragile'] == True
    
    def test_from_dict_reconstructs_package(self):
        """Test that from_dict correctly reconstructs a package."""
        original = Package((8, 8, 8), 4.0, 200.0, "Original", True, False)
        snapshot = original.snapshot()
        
        reconstructed = Package.from_dict(snapshot)
        
        assert reconstructed.size == original.size
        assert reconstructed.weight == original.weight
        assert reconstructed.value == original.value
        assert reconstructed.content_description == original.content_description
        assert reconstructed.is_dangerous == original.is_dangerous
        assert reconstructed.is_fragile == original.is_fragile
    
    def test_from_dict_handles_list_size(self):
        """Test that from_dict converts list size to tuple."""
        data = {
            'size': [1, 2, 3],  # List instead of tuple
            'weight': 1.0,
            'value': 10.0,
            'content_description': "Test",
            'is_dangerous': False,
            'is_fragile': False
        }
        
        pkg = Package.from_dict(data)
        
        assert isinstance(pkg.size, tuple)
        assert pkg.size == (1, 2, 3)


class TestPackagePersistence:
    """Tests for save and from_file methods."""
    
    def test_save_and_load(self, tmp_path):
        """Test saving and loading package from file."""
        # Need to import pickle for save to work
        import pickle
        
        pkg = Package((12, 12, 12), 6.0, 150.0, "Persistence Test", False, False)
        file_path = tmp_path / "test_package.pkl"
        
        pkg.save(str(file_path))
        loaded = Package.from_file(str(file_path))
        
        assert loaded.size == pkg.size
        assert loaded.weight == pkg.weight
        assert loaded.content_description == pkg.content_description
    
    def test_from_file_nonexistent_raises_error(self):
        """Test that from_file raises error for nonexistent file."""
        with pytest.raises(FileNotFoundError):
            Package.from_file("nonexistent_file.pkl")


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
