# -*- coding: utf-8 -*-
"""
Test suite for PaymentArrangement.py

@author: Generated by Antigravity
"""
import pytest
from PaymentArrangement import PaymentMethod, BillingTiming


class TestPaymentMethod:
    """Tests for PaymentMethod enum."""
    
    def test_payment_method_cash_value(self):
        """Test PaymentMethod.cash has correct value."""
        assert PaymentMethod.cash.value == 0
    
    def test_payment_method_card_value(self):
        """Test PaymentMethod.card has correct value."""
        assert PaymentMethod.card.value == 1
    
    def test_payment_method_wire_value(self):
        """Test PaymentMethod.wire has correct value."""
        assert PaymentMethod.wire.value == 2
    
    def test_payment_method_all_members(self):
        """Test that all expected members exist."""
        members = list(PaymentMethod)
        
        assert len(members) == 3
        assert PaymentMethod.cash in members
        assert PaymentMethod.card in members
        assert PaymentMethod.wire in members
    
    def test_payment_method_from_value(self):
        """Test creating PaymentMethod from integer value."""
        assert PaymentMethod(0) == PaymentMethod.cash
        assert PaymentMethod(1) == PaymentMethod.card
        assert PaymentMethod(2) == PaymentMethod.wire
    
    def test_payment_method_invalid_value_raises(self):
        """Test that invalid value raises ValueError."""
        with pytest.raises(ValueError):
            PaymentMethod(99)
    
    def test_payment_method_name_access(self):
        """Test accessing enum member by name."""
        assert PaymentMethod['cash'] == PaymentMethod.cash
        assert PaymentMethod['card'] == PaymentMethod.card
        assert PaymentMethod['wire'] == PaymentMethod.wire


class TestBillingTiming:
    """Tests for BillingTiming enum."""
    
    def test_billing_timing_in_advance_value(self):
        """Test BillingTiming.in_advance has correct value."""
        assert BillingTiming.in_advance.value == 0
    
    def test_billing_timing_on_delivery_value(self):
        """Test BillingTiming.on_delivery has correct value."""
        assert BillingTiming.on_delivery.value == 1
    
    def test_billing_timing_monthly_value(self):
        """Test BillingTiming.monthly has correct value."""
        assert BillingTiming.monthly.value == 2
    
    def test_billing_timing_all_members(self):
        """Test that all expected members exist."""
        members = list(BillingTiming)
        
        assert len(members) == 3
        assert BillingTiming.in_advance in members
        assert BillingTiming.on_delivery in members
        assert BillingTiming.monthly in members
    
    def test_billing_timing_from_value(self):
        """Test creating BillingTiming from integer value."""
        assert BillingTiming(0) == BillingTiming.in_advance
        assert BillingTiming(1) == BillingTiming.on_delivery
        assert BillingTiming(2) == BillingTiming.monthly
    
    def test_billing_timing_invalid_value_raises(self):
        """Test that invalid value raises ValueError."""
        with pytest.raises(ValueError):
            BillingTiming(99)
    
    def test_billing_timing_name_access(self):
        """Test accessing enum member by name."""
        assert BillingTiming['in_advance'] == BillingTiming.in_advance
        assert BillingTiming['on_delivery'] == BillingTiming.on_delivery
        assert BillingTiming['monthly'] == BillingTiming.monthly


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
