# -*- coding: utf-8 -*-
"""
Test suite for PaymentRecord.py

@author: Generated by Antigravity
"""
import pytest
from PaymentRecord import PaymentRecord
from PaymentArrangement import PaymentMethod


class TestPaymentRecordCreation:
    """Tests for PaymentRecord initialization."""
    
    def test_payment_record_creation_cash(self):
        """Test PaymentRecord creation with cash payment."""
        record = PaymentRecord("TXN001", PaymentMethod.cash)
        
        assert record.transaction_ID == "TXN001"
        assert record.method == PaymentMethod.cash
    
    def test_payment_record_creation_card(self):
        """Test PaymentRecord creation with card payment."""
        record = PaymentRecord("TXN002", PaymentMethod.card)
        
        assert record.transaction_ID == "TXN002"
        assert record.method == PaymentMethod.card
    
    def test_payment_record_invalid_method_type_string(self):
        """Test that string method raises TypeError."""
        with pytest.raises(TypeError, match="method provided is invalid"):
            PaymentRecord("TXN001", "cash")
    
    def test_payment_record_invalid_method_type_int(self):
        """Test that integer method raises TypeError."""
        with pytest.raises(TypeError, match="method provided is invalid"):
            PaymentRecord("TXN001", 1)
    
    def test_payment_record_invalid_method_type_none(self):
        """Test that None method raises TypeError."""
        with pytest.raises(TypeError, match="method provided is invalid"):
            PaymentRecord("TXN001", None)


class TestPaymentRecordProperties:
    """Tests for PaymentRecord property accessors."""
    
    @pytest.fixture
    def sample_record(self):
        """Create a sample payment record for testing."""
        return PaymentRecord("TXN12345", PaymentMethod.cash)
    
    def test_transaction_id_property(self, sample_record):
        """Test transaction_ID property."""
        assert sample_record.transaction_ID == "TXN12345"
    
    def test_method_property(self, sample_record):
        """Test method property."""
        assert sample_record.method == PaymentMethod.cash
    
    def test_properties_are_readonly(self, sample_record):
        """Test that properties don't have setters."""
        with pytest.raises(AttributeError):
            sample_record.transaction_ID = "NEW_TXN"
        with pytest.raises(AttributeError):
            sample_record.method = PaymentMethod.card


class TestPaymentRecordSnapshot:
    """Tests for snapshot and from_dict methods."""
    
    def test_snapshot_returns_dict(self):
        """Test that snapshot returns a dictionary."""
        record = PaymentRecord("TXN001", PaymentMethod.cash)
        
        snapshot = record.snapshot()
        
        assert isinstance(snapshot, dict)
        assert snapshot['transaction_ID'] == "TXN001"
        assert snapshot['method'] == PaymentMethod.cash.value
    
    def test_snapshot_with_different_methods(self):
        """Test snapshot with different payment methods."""
        record_cash = PaymentRecord("TXN001", PaymentMethod.cash)
        record_card = PaymentRecord("TXN002", PaymentMethod.card)
        
        assert record_cash.snapshot()['method'] == PaymentMethod.cash.value
        assert record_card.snapshot()['method'] == PaymentMethod.card.value
    
    def test_from_dict_reconstructs_record(self):
        """Test that from_dict correctly reconstructs a PaymentRecord."""
        original = PaymentRecord("TXN999", PaymentMethod.card)
        snapshot = original.snapshot()
        
        reconstructed = PaymentRecord.from_dict(snapshot)
        
        assert reconstructed.transaction_ID == original.transaction_ID
        assert reconstructed.method == original.method
    
    def test_from_dict_with_none_returns_none(self):
        """Test that from_dict with None returns None."""
        result = PaymentRecord.from_dict(None)
        
        assert result is None
    
    def test_roundtrip_snapshot_from_dict(self):
        """Test full roundtrip: create -> snapshot -> from_dict."""
        original = PaymentRecord("ROUNDTRIP001", PaymentMethod.cash)
        
        snapshot = original.snapshot()
        restored = PaymentRecord.from_dict(snapshot)
        
        assert restored.transaction_ID == original.transaction_ID
        assert restored.method == original.method


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
