# -*- coding: utf-8 -*-
"""
Test suite for Vehicle.py

@author: Generated by Antigravity
"""
import pytest
from unittest.mock import MagicMock
from Vehicle import Vehicle, Minivan, MiniTruck, Truck


class TestVehicleAbstract:
    """Tests to verify Vehicle is abstract."""
    
    def test_vehicle_cannot_be_instantiated(self):
        """Test that Vehicle ABC cannot be directly instantiated."""
        with pytest.raises(TypeError, match="abstract"):
            Vehicle("ABC-1234")


class TestMinivan:
    """Tests for Minivan class."""
    
    def test_minivan_creation(self):
        """Test Minivan creation with license plate."""
        van = Minivan("ABC-1234")
        
        assert van.license_plate == "ABC-1234"
    
    def test_minivan_str(self):
        """Test Minivan __str__ representation."""
        van = Minivan("XYZ-9999")
        
        assert str(van) == "minivan (XYZ-9999)"
    
    def test_minivan_cargo_starts_empty(self):
        """Test Minivan has empty cargo initially."""
        van = Minivan("ABC-1234")
        
        assert van.cargo == set()
        assert len(van.cargo) == 0


class TestMiniTruck:
    """Tests for MiniTruck class."""
    
    def test_mini_truck_creation(self):
        """Test MiniTruck creation with license plate."""
        truck = MiniTruck("DEF-5678")
        
        assert truck.license_plate == "DEF-5678"
    
    def test_mini_truck_str(self):
        """Test MiniTruck __str__ representation."""
        truck = MiniTruck("DEF-5678")
        
        assert str(truck) == "mini truck (DEF-5678)"


class TestTruck:
    """Tests for Truck class."""
    
    def test_truck_creation(self):
        """Test Truck creation with license plate."""
        truck = Truck("GHI-0000")
        
        assert truck.license_plate == "GHI-0000"
    
    def test_truck_str(self):
        """Test Truck __str__ representation."""
        truck = Truck("GHI-0000")
        
        assert str(truck) == "truck (GHI-0000)"


class TestVehiclePickUp:
    """Tests for Vehicle pick_up method."""
    
    def test_pick_up_single_order(self):
        """Test picking up a single order."""
        van = Minivan("ABC-1234")
        order = MagicMock()
        
        van.pick_up(order)
        
        assert order in van.cargo
        assert len(van.cargo) == 1
    
    def test_pick_up_multiple_orders(self):
        """Test picking up multiple orders at once."""
        van = Minivan("ABC-1234")
        order1, order2, order3 = MagicMock(), MagicMock(), MagicMock()
        
        van.pick_up(order1, order2, order3)
        
        assert len(van.cargo) == 3
        assert order1 in van.cargo
        assert order2 in van.cargo
        assert order3 in van.cargo
    
    def test_pick_up_duplicate_order(self):
        """Test that picking up same order twice doesn't duplicate."""
        van = Minivan("ABC-1234")
        order = MagicMock()
        
        van.pick_up(order)
        van.pick_up(order)
        
        assert len(van.cargo) == 1


class TestVehicleDeliver:
    """Tests for Vehicle deliver method."""
    
    def test_deliver_order(self):
        """Test delivering an order removes it from cargo."""
        van = Minivan("ABC-1234")
        order = MagicMock()
        van.pick_up(order)
        
        van.deliver(order)
        
        assert order not in van.cargo
        assert len(van.cargo) == 0
    
    def test_deliver_one_of_multiple(self):
        """Test delivering one order keeps others."""
        van = Minivan("ABC-1234")
        order1, order2, order3 = MagicMock(), MagicMock(), MagicMock()
        van.pick_up(order1, order2, order3)
        
        van.deliver(order2)
        
        assert len(van.cargo) == 2
        assert order1 in van.cargo
        assert order3 in van.cargo
        assert order2 not in van.cargo
    
    def test_deliver_nonexistent_order_raises_error(self):
        """Test delivering an order not in cargo raises KeyError."""
        van = Minivan("ABC-1234")
        order = MagicMock()
        
        with pytest.raises(KeyError):
            van.deliver(order)


class TestVehicleCargo:
    """Tests for Vehicle cargo property."""
    
    def test_cargo_returns_copy(self):
        """Test that cargo property returns a copy."""
        van = Minivan("ABC-1234")
        order = MagicMock()
        van.pick_up(order)
        
        cargo = van.cargo
        cargo.clear()
        
        # Original should be unchanged
        assert len(van.cargo) == 1
        assert order in van.cargo


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
