# -*- coding: utf-8 -*-
"""
Test suite for Order.py

@author: Generated by Antigravity
"""
import pytest
from unittest.mock import patch, MagicMock, PropertyMock
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo


class TestServiceEnum:
    """Tests for Service enum."""
    
    def test_service_values(self):
        """Test Service enum values (fee multipliers)."""
        from Order import Service
        
        assert Service.over_night.value == 2.5
        assert Service.express.value == 1.8
        assert Service.standard.value == 1.2
        assert Service.economy.value == 1.0
    
    def test_service_day_property(self):
        """Test Service.day property returns correct days."""
        from Order import Service
        
        assert Service.over_night.day == 1
        assert Service.express.day == 2
        assert Service.standard.day == 7
        assert Service.economy.day == 14


class TestSizeClassEnum:
    """Tests for SizeClass enum."""
    
    def test_size_class_values(self):
        """Test SizeClass enum values."""
        from Order import SizeClass
        
        assert SizeClass.envelope.value == 60
        assert SizeClass.small_box.value == 120
        assert SizeClass.medium_box.value == 250
        assert SizeClass.big_box.value == 450


class TestWeightClassEnum:
    """Tests for WeightClass enum."""
    
    def test_weight_class_values(self):
        """Test WeightClass enum values."""
        from Order import WeightClass
        
        assert WeightClass.extra_light.value == 60
        assert WeightClass.light.value == 120
        assert WeightClass.heavy.value == 250
        assert WeightClass.extra_heavy.value == 450


class TestStatusEnum:
    """Tests for Status enum."""
    
    def test_status_values(self):
        """Test Status enum values."""
        from Order import Status
        
        assert Status.normal.value == 0
        assert Status.delivered.value == 1
        assert Status.delayed.value == 2
        assert Status.broken.value == 3
        assert Status.missing.value == 4


class TestOrderCreation:
    """Tests for Order initialization."""
    
    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        """Setup test fixtures with mocked data path."""
        from Order import Order
        
        self.test_dir = tmp_path / "orders"
        self.test_dir.mkdir()
        
        self.patcher_path = patch.object(Order, '_Order__DATA_PATH', str(self.test_dir))
        self.patcher_cnt = patch.object(Order, '_Order__order_cnt', 0)
        
        self.patcher_path.start()
        self.patcher_cnt.start()
        
        yield
        
        self.patcher_path.stop()
        self.patcher_cnt.stop()
    
    def test_order_creation_basic(self):
        """Test basic Order creation."""
        from Order import Order, Service
        from PaymentArrangement import BillingTiming
        from Location import Destination
        
        origin = Destination("Origin Address")
        dest = Destination("Destination Address")
        
        order = Order(
            "C00001",
            BillingTiming.in_advance,
            Service.standard,
            origin,
            dest,
            "S001",  # collector_ID
            False,   # is_international
            (10, 10, 10),  # size
            5.0,     # weight
            100.0,   # value
            "Test Package",  # description
            False,   # is_dangerous
            False    # is_fragile
        )
        
        assert order.payer == "C00001"
        assert order.ID.startswith("O")
        assert order.service == Service.standard
        assert order.is_international == False
    
    def test_order_id_format(self):
        """Test that Order ID follows expected format."""
        from Order import Order, Service
        from PaymentArrangement import BillingTiming
        from Location import Destination
        
        origin = Destination("Origin")
        dest = Destination("Dest")
        
        order = Order("C00001", BillingTiming.in_advance, Service.economy,
                      origin, dest, "S001", False,
                      (1, 1, 1), 1.0, 10.0, "", False, False)
        
        # ID should be O + 13 digits
        assert order.ID[0] == "O"
        assert len(order.ID) == 14
    
    def test_order_due_date_calculation(self):
        """Test that due date is calculated based on service."""
        from Order import Order, Service
        from PaymentArrangement import BillingTiming
        from Location import Destination
        
        origin = Destination("Origin")
        dest = Destination("Dest")
        
        order = Order("C00001", BillingTiming.in_advance, Service.express,
                      origin, dest, "S001", False,
                      (1, 1, 1), 1.0, 10.0, "", False, False)
        
        # Express = 2 days
        expected_due = order.collection_date + timedelta(days=2)
        assert order.due_date == expected_due
    
    def test_order_initial_status_is_normal(self):
        """Test that new order has normal status."""
        from Order import Order, Service, Status
        from PaymentArrangement import BillingTiming
        from Location import Destination
        
        origin = Destination("Origin")
        dest = Destination("Dest")
        
        order = Order("C00001", BillingTiming.in_advance, Service.economy,
                      origin, dest, "S001", False,
                      (1, 1, 1), 1.0, 10.0, "", False, False)
        
        assert order.status == Status.normal


class TestOrderCalcFee:
    """Tests for Order.calc_fee method."""
    
    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        """Setup test fixtures."""
        from Order import Order
        
        self.test_dir = tmp_path / "orders"
        self.test_dir.mkdir()
        
        self.patcher_path = patch.object(Order, '_Order__DATA_PATH', str(self.test_dir))
        self.patcher_cnt = patch.object(Order, '_Order__order_cnt', 0)
        
        self.patcher_path.start()
        self.patcher_cnt.start()
        
        yield
        
        self.patcher_path.stop()
        self.patcher_cnt.stop()
    
    def test_calc_fee_basic(self):
        """Test basic fee calculation."""
        from Order import Order, Service
        from PaymentArrangement import BillingTiming
        from Location import Destination
        
        origin = Destination("Origin")
        dest = Destination("Dest")
        
        order = Order("C00001", BillingTiming.in_advance, Service.economy,
                      origin, dest, "S001", False,
                      (1, 1, 1), 1.0, 10.0, "", False, False)
        
        fee = order.fee
        
        assert fee is not None
        assert fee > 0
    
    def test_calc_fee_dangerous_adds_surcharge(self):
        """Test that dangerous goods add 500 surcharge."""
        from Order import Order, Service
        from PaymentArrangement import BillingTiming
        from Location import Destination
        
        origin = Destination("Origin")
        dest = Destination("Dest")
        
        # Non-dangerous order
        order1 = Order("C00001", BillingTiming.in_advance, Service.economy,
                       origin, dest, "S001", False,
                       (1, 1, 1), 1.0, 10.0, "", False, False)
        
        # Dangerous order
        order2 = Order("C00002", BillingTiming.in_advance, Service.economy,
                       origin, dest, "S001", False,
                       (1, 1, 1), 1.0, 10.0, "", True, False)
        
        assert order2.fee == order1.fee + 500
    
    def test_calc_fee_fragile_adds_surcharge(self):
        """Test that fragile goods add 100 surcharge."""
        from Order import Order, Service
        from PaymentArrangement import BillingTiming
        from Location import Destination
        
        origin = Destination("Origin")
        dest = Destination("Dest")
        
        # Non-fragile order
        order1 = Order("C00001", BillingTiming.in_advance, Service.economy,
                       origin, dest, "S001", False,
                       (1, 1, 1), 1.0, 10.0, "", False, False)
        
        # Fragile order
        order2 = Order("C00002", BillingTiming.in_advance, Service.economy,
                       origin, dest, "S001", False,
                       (1, 1, 1), 1.0, 10.0, "", False, True)
        
        assert order2.fee == order1.fee + 100


class TestOrderLogging:
    """Tests for Order logging methods."""
    
    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        """Setup test fixtures."""
        from Order import Order
        
        self.test_dir = tmp_path / "orders"
        self.test_dir.mkdir()
        
        self.patcher_path = patch.object(Order, '_Order__DATA_PATH', str(self.test_dir))
        self.patcher_cnt = patch.object(Order, '_Order__order_cnt', 0)
        
        self.patcher_path.start()
        self.patcher_cnt.start()
        
        yield
        
        self.patcher_path.stop()
        self.patcher_cnt.stop()
    
    def test_order_has_initial_log(self):
        """Test that new order has an initial Arrival log."""
        from Order import Order, Service
        from PaymentArrangement import BillingTiming
        from Location import Destination
        from Entry import Arrival
        
        origin = Destination("Origin")
        dest = Destination("Dest")
        
        order = Order("C00001", BillingTiming.in_advance, Service.economy,
                      origin, dest, "S001", False,
                      (1, 1, 1), 1.0, 10.0, "", False, False)
        
        logs = order.all_logs()
        
        assert len(logs) == 1
        assert isinstance(logs[0], Arrival)
    
    def test_last_log_returns_most_recent(self):
        """Test that last_log returns the most recent entry."""
        from Order import Order, Service
        from PaymentArrangement import BillingTiming
        from Location import Destination
        
        origin = Destination("Origin")
        dest = Destination("Dest")
        
        order = Order("C00001", BillingTiming.in_advance, Service.economy,
                      origin, dest, "S001", False,
                      (1, 1, 1), 1.0, 10.0, "", False, False)
        
        last = order.last_log()
        all_logs = order.all_logs()
        
        assert last == all_logs[-1]


class TestOrderPersistence:
    """Tests for Order save and from_ID methods."""
    
    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        """Setup test fixtures."""
        from Order import Order
        
        self.test_dir = tmp_path / "orders"
        self.test_dir.mkdir()
        
        self.patcher_path = patch.object(Order, '_Order__DATA_PATH', str(self.test_dir))
        self.patcher_cnt = patch.object(Order, '_Order__order_cnt', 0)
        
        self.patcher_path.start()
        self.patcher_cnt.start()
        
        yield
        
        self.patcher_path.stop()
        self.patcher_cnt.stop()
    
    def test_save_creates_file(self):
        """Test that save() creates a pickle file."""
        from Order import Order, Service
        from PaymentArrangement import BillingTiming
        from Location import Destination
        
        origin = Destination("Origin")
        dest = Destination("Dest")
        
        order = Order("C00001", BillingTiming.in_advance, Service.economy,
                      origin, dest, "S001", False,
                      (1, 1, 1), 1.0, 10.0, "", False, False)
        
        order.save()
        
        expected_file = self.test_dir / f"{order.ID}.pkl"
        assert expected_file.exists()
    
    def test_from_id_loads_order(self):
        """Test that from_ID correctly loads a saved order."""
        from Order import Order, Service
        from PaymentArrangement import BillingTiming
        from Location import Destination
        
        origin = Destination("Origin")
        dest = Destination("Dest")
        
        order = Order("C00001", BillingTiming.in_advance, Service.economy,
                      origin, dest, "S001", False,
                      (1, 1, 1), 1.0, 10.0, "Test", False, False)
        order.save()
        order_id = order.ID
        
        loaded = Order.from_ID(order_id)
        
        assert loaded.ID == order_id
        assert loaded.payer == "C00001"
    
    def test_from_id_nonexistent_raises_error(self):
        """Test that from_ID raises error for nonexistent ID."""
        from Order import Order
        
        with pytest.raises(FileNotFoundError):
            Order.from_ID("O9999999999999")


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
