# -*- coding: utf-8 -*-
"""
Test suite for Location.py

@author: Generated by Antigravity
"""
import pytest
from unittest.mock import MagicMock
from Location import Location, Destination, Repository


class TestDestination:
    """Tests for the Destination class."""
    
    def test_destination_creation(self):
        """Test basic Destination creation with address."""
        dest = Destination("123 Main St, City")
        
        assert dest.address == "123 Main St, City"
    
    def test_destination_str_returns_address(self):
        """Test that __str__ returns the address."""
        dest = Destination("456 Oak Ave")
        
        assert str(dest) == "456 Oak Ave"
    
    def test_destination_address_is_readonly(self):
        """Test that address property doesn't have a setter (readonly)."""
        dest = Destination("Test Address")
        
        # Should not be able to set address directly
        with pytest.raises(AttributeError):
            dest.address = "New Address"
    
    def test_destination_with_empty_address(self):
        """Test Destination with empty address string."""
        dest = Destination("")
        
        assert dest.address == ""
        assert str(dest) == ""
    
    def test_destination_with_unicode_address(self):
        """Test Destination with unicode characters in address."""
        dest = Destination("台北市信義區信義路五段7號")
        
        assert dest.address == "台北市信義區信義路五段7號"
        assert str(dest) == "台北市信義區信義路五段7號"


class TestRepository:
    """Tests for the Repository class."""
    
    def test_repository_creation(self):
        """Test basic Repository creation with address and name."""
        repo = Repository("100 Warehouse Blvd", "Main Warehouse")
        
        assert repo.address == "100 Warehouse Blvd"
        assert repo.name == "Main Warehouse"
    
    def test_repository_str_returns_name(self):
        """Test that __str__ returns the repository name, not address."""
        repo = Repository("Hidden Address", "Distribution Center")
        
        assert str(repo) == "Distribution Center"
    
    def test_repository_inventory_starts_empty(self):
        """Test that new Repository has empty inventory."""
        repo = Repository("Address", "Name")
        
        assert repo.inventory == set()
        assert len(repo.inventory) == 0
    
    def test_repository_receive_single_order(self):
        """Test receiving a single order."""
        repo = Repository("Address", "Name")
        mock_order = MagicMock()
        
        repo.receive(mock_order)
        
        assert mock_order in repo.inventory
        assert len(repo.inventory) == 1
    
    def test_repository_receive_multiple_orders(self):
        """Test receiving multiple orders at once."""
        repo = Repository("Address", "Name")
        order1, order2, order3 = MagicMock(), MagicMock(), MagicMock()
        
        repo.receive(order1, order2, order3)
        
        assert len(repo.inventory) == 3
        assert order1 in repo.inventory
        assert order2 in repo.inventory
        assert order3 in repo.inventory
    
    def test_repository_ship_single_order(self):
        """Test shipping a single order."""
        repo = Repository("Address", "Name")
        order = MagicMock()
        repo.receive(order)
        
        repo.ship(order)
        
        assert order not in repo.inventory
        assert len(repo.inventory) == 0
    
    def test_repository_ship_multiple_orders(self):
        """Test shipping multiple orders at once."""
        repo = Repository("Address", "Name")
        order1, order2, order3 = MagicMock(), MagicMock(), MagicMock()
        repo.receive(order1, order2, order3)
        
        repo.ship(order1, order3)
        
        assert len(repo.inventory) == 1
        assert order2 in repo.inventory
        assert order1 not in repo.inventory
        assert order3 not in repo.inventory
    
    def test_repository_ship_nonexistent_order(self):
        """Test shipping an order not in inventory (no error)."""
        repo = Repository("Address", "Name")
        order = MagicMock()
        
        # Should not raise error - set subtraction is safe
        repo.ship(order)
        
        assert len(repo.inventory) == 0
    
    def test_repository_receive_duplicate_order(self):
        """Test that receiving same order twice doesn't duplicate."""
        repo = Repository("Address", "Name")
        order = MagicMock()
        
        repo.receive(order)
        repo.receive(order)
        
        assert len(repo.inventory) == 1
    
    def test_repository_inventory_is_copy(self):
        """Test that inventory property returns a copy, not the original."""
        repo = Repository("Address", "Name")
        order = MagicMock()
        repo.receive(order)
        
        # Modify the returned inventory
        inventory = repo.inventory
        inventory.clear()
        
        # Original should be unchanged
        assert len(repo.inventory) == 1
        assert order in repo.inventory


class TestLocationAbstract:
    """Tests to verify Location is abstract."""
    
    def test_location_cannot_be_instantiated(self):
        """Test that Location ABC cannot be directly instantiated."""
        with pytest.raises(TypeError, match="abstract"):
            Location("Test Address")


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
