# -*- coding: utf-8 -*-
"""
Test suite for Entry.py

@author: Generated by Antigravity
"""
import pytest
from unittest.mock import MagicMock, patch
from datetime import datetime
from zoneinfo import ZoneInfo
from Entry import Entry, Transit, Arrival, OtherEvent


class TestEntryAbstract:
    """Tests to verify Entry is abstract."""
    
    def test_entry_cannot_be_instantiated(self):
        """Test that Entry ABC cannot be directly instantiated."""
        with pytest.raises(TypeError, match="abstract"):
            Entry("test_signature")


class TestTransit:
    """Tests for the Transit entry class."""
    
    @pytest.fixture
    def mock_vehicle(self):
        """Create a mock vehicle."""
        vehicle = MagicMock()
        vehicle.__str__ = MagicMock(return_value="Truck ABC-1234")
        return vehicle
    
    @pytest.fixture
    def mock_origin(self):
        """Create a mock origin location."""
        origin = MagicMock()
        origin.__str__ = MagicMock(return_value="Warehouse A")
        return origin
    
    @pytest.fixture
    def mock_destination(self):
        """Create a mock destination location."""
        dest = MagicMock()
        dest.__str__ = MagicMock(return_value="Distribution Center B")
        return dest
    
    def test_transit_creation(self, mock_vehicle, mock_origin, mock_destination):
        """Test basic Transit creation."""
        transit = Transit("S001", mock_vehicle, mock_origin, mock_destination)
        
        assert transit.signature == "S001"
        assert transit.vehicle == mock_vehicle
        assert transit.origin == mock_origin
        assert transit.destination == mock_destination
    
    def test_transit_timestamp_is_set(self, mock_vehicle, mock_origin, mock_destination):
        """Test that Transit has a timestamp set on creation."""
        transit = Transit("S001", mock_vehicle, mock_origin, mock_destination)
        
        assert transit.time_stamp is not None
        assert isinstance(transit.time_stamp, datetime)
    
    def test_transit_str_contains_all_info(self, mock_vehicle, mock_origin, mock_destination):
        """Test that __str__ contains vehicle, origin, and destination."""
        transit = Transit("S001", mock_vehicle, mock_origin, mock_destination)
        
        result = str(transit)
        
        assert "Warehouse A" in result
        assert "Truck ABC-1234" in result
        assert "Distribution Center B" in result
        assert "shipped" in result.lower()
    
    def test_transit_summarize_returns_str(self, mock_vehicle, mock_origin, mock_destination):
        """Test that summarize() returns the same as __str__."""
        transit = Transit("S001", mock_vehicle, mock_origin, mock_destination)
        
        assert transit.summarize() == str(transit)


class TestArrival:
    """Tests for the Arrival entry class."""
    
    @pytest.fixture
    def mock_destination(self):
        """Create a mock destination location."""
        dest = MagicMock()
        dest.__str__ = MagicMock(return_value="Customer Address")
        return dest
    
    def test_arrival_creation(self, mock_destination):
        """Test basic Arrival creation."""
        arrival = Arrival("S002", mock_destination)
        
        assert arrival.signature == "S002"
        assert arrival.destination == mock_destination
    
    def test_arrival_timestamp_is_set(self, mock_destination):
        """Test that Arrival has a timestamp set on creation."""
        arrival = Arrival("S002", mock_destination)
        
        assert arrival.time_stamp is not None
        assert isinstance(arrival.time_stamp, datetime)
    
    def test_arrival_str_contains_destination(self, mock_destination):
        """Test that __str__ contains destination info."""
        arrival = Arrival("S002", mock_destination)
        
        result = str(arrival)
        
        assert "Customer Address" in result
        assert "arrived" in result.lower()
    
    def test_arrival_summarize_returns_str(self, mock_destination):
        """Test that summarize() returns the same as __str__."""
        arrival = Arrival("S002", mock_destination)
        
        assert arrival.summarize() == str(arrival)


class TestOtherEvent:
    """Tests for the OtherEvent entry class."""
    
    def test_other_event_creation_with_description(self):
        """Test OtherEvent creation with both summary and description."""
        event = OtherEvent("S003", "Package Damaged", "Minor dent on corner")
        
        assert event.signature == "S003"
        assert event.summary == "Package Damaged"
        assert event.detail == "Minor dent on corner"
    
    def test_other_event_creation_without_description(self):
        """Test OtherEvent creation with only summary (description defaults to summary)."""
        event = OtherEvent("S003", "Delivered to neighbor")
        
        assert event.summary == "Delivered to neighbor"
        assert event.detail == "Delivered to neighbor"
    
    def test_other_event_timestamp_is_set(self):
        """Test that OtherEvent has a timestamp set on creation."""
        event = OtherEvent("S003", "Test Event")
        
        assert event.time_stamp is not None
        assert isinstance(event.time_stamp, datetime)
    
    def test_other_event_summarize_combines_summary_and_detail(self):
        """Test that summarize() combines summary and detail."""
        event = OtherEvent("S003", "Delay", "Weather conditions")
        
        result = event.summarize()
        
        assert "Delay" in result
        assert "Weather conditions" in result
    
    def test_other_event_str_contains_timestamp_and_summary(self):
        """Test that __str__ contains timestamp and summarize content."""
        event = OtherEvent("S003", "Customs Hold", "Awaiting inspection")
        
        result = str(event)
        
        assert "Customs Hold" in result
        assert "Awaiting inspection" in result
    
    def test_other_event_with_empty_summary(self):
        """Test OtherEvent with empty summary string."""
        event = OtherEvent("S003", "")
        
        assert event.summary == ""
        assert event.detail == ""
    
    def test_other_event_with_unicode_content(self):
        """Test OtherEvent with unicode characters."""
        event = OtherEvent("S003", "配送延遲", "因颱風影響延後一天")
        
        assert event.summary == "配送延遲"
        assert event.detail == "因颱風影響延後一天"


class TestEntryTimestamp:
    """Tests for Entry timestamp behavior."""
    
    def test_timestamp_uses_taipei_timezone(self):
        """Test that timestamp is in Asia/Taipei timezone."""
        from Location import Destination
        dest = Destination("Test")
        arrival = Arrival("S001", dest)
        
        # Check timezone info
        assert arrival.time_stamp.tzinfo is not None
        assert str(arrival.time_stamp.tzinfo) == "Asia/Taipei"
    
    def test_different_entries_have_different_timestamps(self):
        """Test that entries created at different times have different timestamps."""
        import time
        from Location import Destination
        dest = Destination("Test")
        
        arrival1 = Arrival("S001", dest)
        time.sleep(0.01)  # Small delay
        arrival2 = Arrival("S002", dest)
        
        # Timestamps should be different (or at least not exactly equal in most cases)
        # This is a weak test but demonstrates the concept
        assert arrival1.time_stamp <= arrival2.time_stamp


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
