# -*- coding: utf-8 -*-
"""
Test suite for Bill.py

@author: Generated by Antigravity
"""
import pytest
from unittest.mock import MagicMock
from datetime import date, timedelta
from Bill import Bill, MonthlyBill, verify_transaction
from PaymentArrangement import PaymentMethod


class MockCustomer:
    """Mock Customer for testing Bill."""
    def __init__(self, id="C00001", bill_cnt=0):
        self.ID = id
        self.bill_cnt = bill_cnt


class MockOrder:
    """Mock Order for testing Bill."""
    def __init__(self, id="O000010001", fee=100.0):
        self.ID = id
        self.fee = fee


class TestVerifyTransaction:
    """Tests for verify_transaction function."""
    
    def test_verify_transaction_returns_true(self):
        """Test that mock verify_transaction always returns True."""
        assert verify_transaction("TXN001", 100.0) == True
        assert verify_transaction("", 0) == True


class TestBillCreation:
    """Tests for Bill initialization."""
    
    def test_bill_creation_with_order(self):
        """Test Bill creation with an order."""
        customer = MockCustomer()
        order = MockOrder(fee=150.0)
        
        bill = Bill(customer, order)
        
        assert bill.outer == customer
        assert bill.amount == 150.0
        assert bill.ID.startswith("B")
        assert order.ID in bill.manifest
    
    def test_bill_creation_with_none_order(self):
        """Test Bill creation with None order."""
        customer = MockCustomer()
        
        bill = Bill(customer, None)
        
        assert bill.amount == 0
        assert len(bill.manifest) == 0
    
    def test_bill_id_format(self):
        """Test that Bill ID follows expected format."""
        customer = MockCustomer(id="C00005", bill_cnt=3)
        order = MockOrder()
        
        bill = Bill(customer, order)
        
        # ID should be B + customer_id[1:] + bill_cnt formatted
        assert bill.ID.startswith("B00005")
    
    def test_bill_initial_status(self):
        """Test Bill initial status values."""
        customer = MockCustomer()
        order = MockOrder()
        
        bill = Bill(customer, order)
        
        assert bill.issue_status == False
        assert bill.payment_status == False
        assert bill.due_date is None
        assert bill.payment_record is None


class TestBillPayment:
    """Tests for Bill payment methods."""
    
    def test_pay_marks_bill_as_paid(self):
        """Test that pay() sets payment_status to True."""
        customer = MockCustomer()
        order = MockOrder()
        bill = Bill(customer, order)
        
        bill.pay("TXN001", PaymentMethod.cash)
        
        assert bill.payment_status == True
        assert bill.payment_record is not None
        assert bill.payment_record.transaction_ID == "TXN001"
        assert bill.payment_record.method == PaymentMethod.cash
    
    def test_verify_payment_returns_status(self):
        """Test that verify_payment() returns payment status."""
        customer = MockCustomer()
        order = MockOrder()
        bill = Bill(customer, order)
        
        assert bill.verify_payment() == False
        
        bill.pay("TXN001", PaymentMethod.card)
        
        assert bill.verify_payment() == True


class TestBillIssue:
    """Tests for Bill issue method."""
    
    def test_issue_sets_status_and_due_date(self):
        """Test that issue() sets issue_status and due_date."""
        customer = MockCustomer()
        order = MockOrder()
        bill = Bill(customer, order)
        
        bill.issue()
        
        assert bill.issue_status == True
        assert bill.due_date is not None
        # Due date should be 15 days from today
        expected_due = date.today() + timedelta(days=15)
        assert bill.due_date == expected_due


class TestBillManifest:
    """Tests for Bill manifest property."""
    
    def test_manifest_returns_copy(self):
        """Test that manifest property returns a copy."""
        customer = MockCustomer()
        order = MockOrder()
        bill = Bill(customer, order)
        
        manifest = bill.manifest
        manifest.append("O999999")
        
        # Original should be unchanged
        assert "O999999" not in bill.manifest
        assert len(bill.manifest) == 1


class TestBillSnapshot:
    """Tests for Bill snapshot and from_dict."""
    
    def test_snapshot_returns_dict(self):
        """Test that snapshot returns a dictionary."""
        customer = MockCustomer()
        order = MockOrder(id="O00001", fee=200.0)
        bill = Bill(customer, order)
        
        snapshot = bill.snapshot()
        
        assert isinstance(snapshot, dict)
        assert snapshot['amount'] == 200.0
        assert 'O00001' in snapshot['manifest']
    
    def test_snapshot_includes_due_date_when_issued(self):
        """Test that snapshot includes due_date when bill is issued."""
        customer = MockCustomer()
        order = MockOrder()
        bill = Bill(customer, order)
        bill.issue()
        
        snapshot = bill.snapshot()
        
        assert 'due_date' in snapshot
    
    def test_snapshot_includes_payment_record_when_paid(self):
        """Test that snapshot includes payment_record when bill is paid."""
        customer = MockCustomer()
        order = MockOrder()
        bill = Bill(customer, order)
        bill.pay("TXN001", PaymentMethod.cash)
        
        snapshot = bill.snapshot()
        
        assert 'payment_record' in snapshot


class TestMonthlyBill:
    """Tests for MonthlyBill class."""
    
    def test_monthly_bill_creation(self):
        """Test MonthlyBill creation."""
        customer = MockCustomer()
        order = MockOrder(fee=100.0)
        
        bill = MonthlyBill(customer, order)
        
        assert bill.amount == 100.0
        assert bill.due_date is not None
    
    def test_monthly_bill_due_date_is_next_month_15th(self):
        """Test that due_date is 15th of next month."""
        customer = MockCustomer()
        order = MockOrder()
        
        bill = MonthlyBill(customer, order)
        
        assert bill.due_date.day == 15
    
    def test_monthly_bill_add_item(self):
        """Test adding items to MonthlyBill."""
        customer = MockCustomer()
        order1 = MockOrder(id="O00001", fee=100.0)
        order2 = MockOrder(id="O00002", fee=50.0)
        
        bill = MonthlyBill(customer, order1)
        bill.add_item(order2)
        
        assert bill.amount == 150.0
        assert len(bill.manifest) == 2
        assert "O00001" in bill.manifest
        assert "O00002" in bill.manifest
    
    def test_monthly_bill_add_item_after_issue_raises_error(self):
        """Test that adding to issued bill raises RuntimeError."""
        customer = MockCustomer()
        order1 = MockOrder()
        order2 = MockOrder()
        
        bill = MonthlyBill(customer, order1)
        bill.issue()
        
        with pytest.raises(RuntimeError, match="Adding to an issued bill"):
            bill.add_item(order2)
    
    def test_monthly_bill_month_property(self):
        """Test month property returns correct month."""
        customer = MockCustomer()
        order = MockOrder()
        
        bill = MonthlyBill(customer, order)
        
        # month should be valid (1-12)
        assert 1 <= bill.month <= 12


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
